[package]
name = "test-opengl"
version = "0.1.0"
authors = ["thexivn <ivan.ghezzi.tux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "0.22.3"
ply-rs = "0.1.2"
cgmath = "0.17.0"